### ISSUE TITLE
link the results of a search to the batch search

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues#39]
When searching for a phenotype, we have targets and diseases retrieved.

Can we offer a facet with the targets in a list and then link them to the batch search tool?

**Comment by emepyc** [comment]
There are certainly some useful use cases for sending lists of genes to the batch search page (top targets associated to a disease, targets in a pathway, related targets to another target...).

There are several problems with the one you propose:

1) It is not possible to know if the user searched for a phenotype or any other entity. In any case we always return a (possible) list of targets and diseases.

2) The search works on a semantic level and not on a functional level. For example, if I search for 'top' I get 134 targets retrieved because their name (or a synonym) happens to match that string (the top hits are topoisomerases, but there are many others that are not). There is no sense in treating those genes as functionally related and run the batch search on them.

**Comment by nikiforosk** [comment]
As Miguel mentioned, the targets that show up on the search results for e.g. inflammation are not necessarily associated with inflammation (i.e. this page doesn't take into account the evidence for an association with inflammation): https://www.targetvalidation.org/search?src=q:inflammation,p:1,f:target

Several people, however, do interpret the search results page in a similar way as the associations page. One way to address this may be to replace the header "Search results for X" with "What did you mean by X?" because this page is really asking people to select a target or a disease as named in Open Targets for the search term that they used.

So a better place to do what Denise is suggesting is the associations page, maybe after you have applied a filter e.g. for a pathway: https://www.targetvalidation.org/disease/MP_0001845/associations?fcts=pathway:R-HSA-6785807

But what exactly are people after when they want to perform batch search on this filtered list? Knowing this will help us understand how important this use case is.

**Comment by deniseOme** [comment]
They are after serendipity.
It's not useful for them to work on the targets that are already linked to multiple sclerosis.
They want to start with targets selected from in a given pathway or phenotype.

This phenotype/serendipity was discussed with Patrick Vallance when he visited us last year. Not sure if @gkos-bio has been thinking about ways to address this.

**Comment by emepyc** [comment]
I think we should integrate more batch search into the flows we have (several examples have been given in this thread). I will work on this. But I don't think the search results is a good place to collect lists of genes to analyse in the batch search page.
I'm closing this for now.
